### ISSUE TITLE
Failing require on a case-sensitive filesystem

### ISSUE THREAD

**Issue by AggroBoy** [daumiller/ssdp#1]
In producer.rb, `require 'SecureRandom'` fails on linux (but not usually OS X or Windows), because the file is `securerandom`, and linux's default filesystem is case sensitive. I edited the `require` to all lower case in my local install and it worked as expected after that.

**Comment by daumiller** [comment]
Thank you for the report!
This is fixed in 1.1.3 / as of commit ce33b02.

**Comment by AggroBoy** [comment]
I just grabbed it, and everything's working great. Thanks for the quick fix. :+1:
