### ISSUE TITLE
`IO.select` times out, never returns ready

### ISSUE THREAD

**Issue by janfoeh** [daumiller/ssdp#4]
I have several UPnP devices on my network, and I'm trying to enumerate them with `SSDP::Consumer.new.search(service: 'ssdp:all')`.

Unfortunately, `.search` never returns anything, because `IO.select` in `consumer.rb#112` always times out without ever returning ready. If I replace it with

```
ready = IO.select [@search_socket], nil, nil, 3
puts "ready: #{ready}, remaining: #{remaining}"
```

I get the output

```
ready: , remaining: 30
ready: , remaining: 27
ready: , remaining: 24
ready: , remaining: 21
ready: , remaining: 18
ready: , remaining: 15
ready: , remaining: 12
ready: , remaining: 9
ready: , remaining: 6
ready: , remaining: 3
=> []
```

I can discover my devices through another library, the Eventmachine-based [Playful](https://github.com/turboladen/playful), so my network shouldn't be the culprit.

Do you have any idea why I might be unable to read from the UDP socket? Any help would be appreciated. I'm on OSX 10.10, if that makes a difference.

Thanks in advance and happy holidays!

**Comment by daumiller** [comment]
That's odd... I'm also running 10.10.5, and haven't had that kind of problem.

Could you try running the `test_consumber.rb` file and see if any of the tests pass for you?
(https://github.com/daumiller/ssdp/blob/master/test/test_consumer.rb)
_It can only test local-local, but should be able to tell if it's something up with the socket options._

**Comment by janfoeh** [comment]
Thanks for the quick response! `test_consumer.rb` runs without a hitch (after I prepended `../lib` to the load path).

I tried using `recvfrom_nonblock`, as in

``` ruby
    start_time = Time.now
    begin
      message, producer = @search_socket.recvfrom_nonblock(options[:maxpack])

      if options[:filter].nil?
        responses << process_ssdp_packet(message, producer)
      else
        result = process_ssdp_packet message, producer
        responses << result if options[:filter].call(result)
      end

    rescue IO::WaitReadable
      elapsed = (Time.now - start_time).to_i

      if elapsed <= options[:timeout]
        IO.select([@search_socket], nil, nil, 3)
        retry
      end
    end
```

but that made no difference either — `recvfrom_nonblock` always throws `IO:WaitReadable`, and `IO.select` always times out. I don't have much experience with socket programming, so I'm a bit stumped here.

**Comment by daumiller** [comment]
It, or at least something, definitely was wrong in my code.
I just made a commit and published version **1.1.5**.
Would you mind giving it a try now and seeing what your results are?

Apparently, I've only specifically tested against devices that don't require an `MX` parameter be present; but there are many devices that won't respond without it. Also, some of my casing was out-of-spec....

Thanks for the report!

**Comment by janfoeh** [comment]
I've tried 1.1.5, and unfortunately do not see any changes. Sorry for not mentioning it, but I actually already tried fixing the case of the header keys and adding the MX header, because I wanted to mirror the request I saw from Playful. I also tried futzing with different line endings (\r, \r\n..), to no avail.

Thank you again for your amazingly prompt help!

**Comment by daumiller** [comment]
Sorry I never got anywhere with this issue; I was never able to reproduce. I just wanted to check in to see if you ever found a solution? If not I'll leave this open, in case it comes up again. Thanks!

**Comment by daumiller** [comment]
If anybody else ends up on this issue, check out [PR #8](https://github.com/daumiller/ssdp/pull/8) for something to try out.
(Not) Binding to a specific interface could possibly be the issue.
If so, either way, feel free to leave a comment here.
